server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_app?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: kenny

  jpa:
    hibernate:
      ddl-auto: create-drop

    database-platform: org.hibernate.dialect.MySQL8Dialect
